### ISSUE TITLE
What to do with stand-alone townhouses

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#109]
In the [documentation](https://hescore-hpxml.readthedocs.io/en/latest/translation/about.html#id3) we say that if a townhouse is "stand-alone" then the `Site/Surroundings` isn't needed. 

The code is currently requiring it:
https://github.com/NREL/hescore-hpxml/blob/master/hescorehpxml/__init__.py#L841-L853

I think it should be required if it is a townhouse because that's a defining characteristic of a townhouse. Let's change the documentation and maybe update the error messages to make that less confusing.

cc @yzhou601

**Comment by lirainer** [comment]
@nmerket It appears to me that this is correct as is. If `about/shape` is *town_house* then `Site/Surroundings` should not be allowed to be set to *stand-alone* as that would indicate that the home is single family *detached*. See the BEDES definition of *stand-alone* in [Vertical Surroundings](https://bedes.lbl.gov/bedes-online/vertical-surroundings): 
> Single family, detached premises are stand-alone structures with outside walls that do not touch any other dwelling. Structure must not share systems (e.g., HVAC or utilities).

**Comment by yzhou601** [comment]
Thanks @nmerket @lirainer , sounds good to just update docs/error messages to eg. suggest a change of its ResidentialFacilityType, etc.

**Comment by lirainer** [comment]
Rereading my note I realize I should have said that I think the code is okay as is, but that yes, the documentation for `stand-alone` should be changed to *not translated*.

**Comment by nmerket** [comment]
Sounds good. I'll make a change to the docs and maybe update the error message to be more descriptive.
