### ISSUE TITLE
Better handle windows attached to foundation walls

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#111]
If a window is attached to a foundation wall it will try to determine the orientation from the wall but won't be able to find it (It's not looking for foundation walls and they don't have orientation anyway). We should fall back to using the orientation from the window itself in that case.

**Comment by shorowit** [comment]
Perhaps I'm just not understanding... but shouldn't you _always_ prioritize using the orientation from the window if available?

**Comment by nmerket** [comment]
Maybe we should, but that's not what's happening now.
