### ISSUE TITLE
Return cleaner errors

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#12]
This has two components:
- [x] Convert assert statements into `TranslationError` and add more as necessary
- [x] Handle `TranslationError` without returning a traceback but still returning an errorcode.

**Comment by nmerket** [comment]
@lirainer I'm assigning this one to you. Go ahead and close it when you have confirmed that it works as you want it to on your end.

**Comment by nmerket** [comment]
@lirainer Sorry to keep bugging you about this, but this is the last issue I have open on this milestone and I'd like to get it closed. Have you been able to test the error messages coming out of the script now to see if it'll work better for you guys? I can send you an HPXML file that I know will error if that helps. Let me know.

**Comment by lirainer** [comment]
I have verified that the errors are getting returned in a good format and that it no longer returns a traceback for xml failures. There are a few range checks that need to be added, but better to do that in a new issue.
