### ISSUE TITLE
HPXML v3 attic roof attachment

### ISSUE THREAD

**Issue by yzhou601** [NREL/hescore-hpxml#120]
HPXML v3.0 now allows multiple [`AttachedToRoof`](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Enclosure/Attics/Attic/AttachedToRoof) elements in `Attic`. Our current workflow (v2) only allows one-to-one attachment. Should we consider handling that for v3? @nmerket

**Comment by nmerket** [comment]
Maybe try something [like this](https://hescore-hpxml.readthedocs.io/en/latest/translation/zone_roof.html#roof-r-value)

**Comment by nmerket** [comment]
Closed in #121
