### ISSUE TITLE
Export an HPXML file scrubbed of PII 

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#125]
It would be helpful to be able have the HPXML file a user submits for support and debugging. However, we want to remove any personally identifiable information, so let's add a flag that optionally writes the imported HPXML file with the following elements removed

- All data under “Customer”
- Under “Building/Site/Address”, All data with “Address Type” = “Mailing” should be removed (I am assuming the “Street” address type is where we get that information for HEScore)
- All data under “Health and Safety”
- All data under “Building/Building Details/Building Summary/Building Occupancy”
- All data under “Building Summary/Annual Energy Use”
- All data under “Utility”
- All data under “Consumption”
- All data under “Building/CustomerID”.

cc @lirainer @gmdickey

**Comment by lirainer** [comment]
Scrubbed file will be archived in S3 by the hescore API method `submit_hpxml_input`. See [hes-api-ci issue 262](https://gitlab.hescloud.net/hes-api-code/hes-api-ci/-/issues/262). File will be saved to S3 bucket as follows:
* Bucket: hes-hpxml-[env] where env is dev, prd, sbx, stg.
* File name: st-[env]-[building_id].xml
