### ISSUE TITLE
Validate numeric input ranges

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#13]
HEScore has valid ranges accepted for each of their input fields. They are documented in the `submit_inputs` call. The translator should maintain valid inputs and throw errors when necessary.

**Comment by nmerket** [comment]
@lirainer I believe I added all the range checks in the `submit_inputs` xsd in this ticket. Let me know if there are others.

**Comment by lirainer** [comment]
NumberofBedrooms accepts any positive number. I thought this was due to not being range checked but it is because the value is set to a max of 10 [here] (https://github.com/NREL/hescore-hpxml/blob/master/code/hpxml_to_hescore.py#L544). I think it would be better to return an error.

**Comment by nmerket** [comment]
Ah, yes that. I was just applying the API rules that @gmdickey sent me that state:

> Number of bedrooms - if greater than 10, use 10.

**Comment by lirainer** [comment]
Fine with me to leave as is. Maybe check with Glenn to see which he would
prefer.

Regards...

   ...leo

**Comment by gmdickey** [comment]
I would leave it as is.

Glenn Dickey
Residential Buildings Technical Director
SRA International, Inc.
6003 Executive Boulevard, #400
Rockville, MD 20852
240-514-2859 (desk)
240-514-2601 (fax)

**Comment by nmerket** [comment]
Done. closing.
