### ISSUE TITLE
Check attic wall type when getting knee walls

### ISSUE THREAD

**Issue by aspeake** [NREL/hescore-hpxml#146]
When getting attic knee walls, this [method](https://github.com/NREL/hescore-hpxml/blob/master/hescorehpxml/hpxml3.py#L63-L74) expects all attic `AttachedToWall` fields to be knee walls, and throws an error when a different wall type is inputted (such as gable walls):

```ERROR:ElementNotFoundError:Can't find element Building///Wall[SystemIdentifier/@id=$kneewallid][AtticWallType="knee wall"] with args {'kneewallid': 'Surface_16'}```

**Comment by nmerket** [comment]
@aspeake Can you provide me a minimum example file that hits this issue?
