### ISSUE TITLE
Move external_building_id to building_address

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#147]
[In this repo](https://github.com/NREL/hescore-hpxml/blob/e5af84582b4524ad92bac0a9f153051f2d39f5eb/hescorehpxml/base.py#L879) we're placing the `external_building_id` under `building.about`. 

In the HEScore API documentation it says that it should be sent with `submit_address` which gets put in `building_address` in this tool. 

That change is easy enough to make here. @thepriestscottage @lirainer, have you been reading it out of the other location up to this point? If so, we should probably coordinate changing that. 

cc @bpark1327

**Comment by lirainer** [comment]
@nmerket This is only used by third party API users so we don't ever use it in our workflow but just pass it along. It gets submitted by `submit_address (building_address/external_building_id)` and retrieved using `retrieve_inputs (building_inputs/about/external_building_id)`.

**Comment by nmerket** [comment]
@lirainer Yes, the API expects that. But this script is used when someone calls `submit_hpxml_inputs`. We pass the `external_building_id` [through from the hpxml file](https://hescore-hpxml.readthedocs.io/en/latest/translation/about.html#external-building-id). We're currently putting it in `building.about.external_building_id`. According to the API docs as mentioned above, it _should_ be in `building_address.external_building_id`. I've never heard any complaints about it meaning either 1.) it's being silently ignored because it's in the wrong place, or 2.) you guys are grabbing it out of `building.about.external_building_id` and putting it where it should go when you parse the json output of this program. Either way, we think we should put it in the right place to match what's in the API, but I wanted to check in with you that it wasn't going to break what's happening on your end when you parse this output.

**Comment by lirainer** [comment]
@nmerket Sorry, I'm being a bit dense - now I understand. Here is the only place we deal with that element of the json output. From [line 1040 of St_api_handler](https://gitlab.hescloud.net/hes-api-code/hes-api-ci/-/blob/master/src/hes-lib/St/St_api_handler.php#L1040):
```
        $address_request->building_address->external_building_id  = $converted_inputs['building']['about']['external_building_id'];
```
Where `$converted_inputs` is the json file. So, yes, if you move it to `building_address.external_building_id` it will break our code.

**Comment by shorowit** [comment]
@lirainer will update the API to look for the new location (and fallback to the current location for backwards compatibility).

**Comment by lirainer** [comment]
LBL API issue is [#291](https://gitlab.hescloud.net/hes-api-code/hes-api-ci/-/issues/291)
