### ISSUE TITLE
Verify handling of extra surfaces from ResStock HPXML files

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#155]
Double check that irrelevant surfaces are being ignored.

**Comment by shorowit** [comment]
E.g., exterior walls of garages.

**Comment by nmerket** [comment]
@shorowit @aspeake Do you have some files I could test this with?

**Comment by aspeake** [comment]
This file has a garage, and may be a good place to start: https://github.com/NREL/hescore-hpxml/blob/resstock-hes/tests/resstock_test/xmls/17-workflow-baseline-in.xml

All the files in https://github.com/NREL/hescore-hpxml/tree/resstock-hes/tests/resstock_test/xmls were generated via ResStock, so the rest of those could be helpful as well.

**Comment by nmerket** [comment]
More potential examples from @shorowit:

- crawlspace slab (a.k.a. "rat slab")
- basement slab
- conditioned basement ceiling
- any surface on a garage
- bonus room over a garage

**Comment by shorowit** [comment]
@aspeake needs to regenerate the HPXML files (the above links no longer work).

**Comment by aspeake** [comment]
> 
> 
> @aspeake needs to regenerate the HPXML files (the above links no longer work).

I re-added the files, and updated the links above

**Comment by nmerket** [comment]
@bpark1327 to add some of the files that exercise these extra surfaces as tests in this repo.

**Comment by nmerket** [comment]
from @shorowit: try using bigger numbers to make sure it would change if it was using the surfaces it shouldn't

**Comment by bpark1327** [comment]
> 
> 
> from @shorowit: try using bigger numbers to make sure it would change if it was using the surfaces it shouldn't

Addressed it [here](https://github.com/NREL/hescore-hpxml/pull/162/commits/0b35c07bf1fcb748b7410fab75710d9d5d1ba76b).
