### ISSUE TITLE
Handle Assembly R-values

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#156]
Walls and Roof R-values in OpenStudio-HPXML are specified as assembly R-values, but hescore-hpxml expects layers with nominal R-values. So, most surfaces are coming through with R-0.

**Comment by shorowit** [comment]
https://github.com/NREL/OpenStudio-HEScore/blob/master/rulesets/HEScoreRuleset/resources/lu_wall_eff_rvalue.csv
https://github.com/NREL/OpenStudio-HEScore/blob/master/rulesets/HEScoreRuleset/resources/lu_roof_eff_rvalue.csv

**Comment by nmerket** [comment]
Left to do:
- [ ] Roofs
- [ ] Ceilings
- [ ] Floors
- [ ] Knee Walls?

(not foundation walls)
