### ISSUE TITLE
Change attic mapping for 2015 release

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#16]
Change the attic mapping to 

HPXML           |       HEScore
------------  |  -------------
cape cod    |           cath_ceiling
cathedral ceiling   |   cath_ceiling
flat roof       |       cath_ceiling
unvented attic     |    ~~vented_attic~~ **unvented_attic**
vented attic     |      vented_attic
venting unknown attic | vented_attic
other           |       *not translated*

when v2015 is released and supports that.

**Comment by nmerket** [comment]
@lirainer 
Just checking. Do I still want to do this? I didn't see anything in the [API differences](https://developers.buildingsapi.lbl.gov/hescore/documentation/hescore-api-methods-2015)

**Comment by lirainer** [comment]
@nmerket 
No, that dropped off the change list for the time being, so our attic types are the same as for 2014.
