### ISSUE TITLE
Multiple ducts translation

### ISSUE THREAD

**Issue by bpark1327** [NREL/hescore-hpxml#167]
**Describe the bug**
If there are two ducts located in the same space type, it seems that they get combined into one duct. When both ducts are either insulated or uninsulated, it's not a problem. But when one duct is insulated and the other duct is uninsulated, combining these ducts into one duct can be a problem. For example, 
```
<AirDistribution>
    <Ducts>
        <DuctInsulationMaterial>
            <None/>
        </DuctInsulationMaterial>
        <DuctLocation>attic</DuctLocation>
        <FractionDuctArea>0.5</FractionDuctArea>
    </Ducts>
    <Ducts>
        <DuctInsulationMaterial>
            <Unknown/>
        </DuctInsulationMaterial>
        <DuctLocation>attic</DuctLocation>
        <FractionDuctArea>0.5</FractionDuctArea>
    </Ducts>
</AirDistribution>
```
these ducts are translated into
```
"hvac_distribution": [
    {
        "name": "duct1",
        "location": "uncond_attic",
        "fraction": 100,
        "insulated": true,
        "sealed": false
    }
]
```

**To Reproduce**
Please see the attched HPXML
[hescore_min_v3_duct_test_attic.xml.txt](https://github.com/NREL/hescore-hpxml/files/7281567/hescore_min_v3_duct_test_attic.xml.txt)

**Expected behavior**
I think what we expect to see is
```
"hvac_distribution": [
    {
        "name": "duct1",
        "location": "uncond_attic",
        "fraction": 50,
        "insulated": false,
        "sealed": false
    },
    {
        "name": "duct2",
        "location": "uncond_attic",
        "fraction": 50,
        "insulated": true,
        "sealed": false
    }
]
```

**Environment (please complete the following information):**
 - OS: Windows
 - Python Version: 3.9.2

**Comment by nmerket** [comment]
If there are fewer than 3 ducts, don't combine them. If there are more than 3, combine them by location.
