### ISSUE TITLE
Translate AirInfiltrationMeasurement without TypeOfInfiltrationMeasurement

### ISSUE THREAD

**Issue by bpark1327** [NREL/hescore-hpxml#186]
**Is your feature request related to a problem? Please describe.**
Currently, the translator requires `TypeOfInfiltrationMeasurement` to translate `AirInfiltrationMeasurement`. The translator does not correctly handle `AirInfiltrationMeasurement` in HPXML files generated by `BuildResidentialHPXML` because they do not have `TypeOfInfiltrationMeasurement`.

**Describe the solution you'd like**
Translate `AirInfiltrationMeasurement` without `TypeOfInfiltrationMeasurement` into "blower_door_test" in HEScore JSON files.

**Describe alternatives you've considered**
Translate `AirInfiltrationMeasurement` if there is a CFM50 or ACH50 measurement even without `TypeOfInfiltrationMeasurement`.

**Additional context**

**Comment by nmerket** [comment]
Also throw an error if there isn't _any_ `AirInfiltrationMeasurement` or if there is one but it doesn't have either of the required sub elements.
