### ISSUE TITLE
Duct Location - Garage - HPXML Translator Mapping Adjustment

### ISSUE THREAD

**Issue by torstenglidden** [NREL/hescore-hpxml#196]
Requesting adjustment of Duct Location for HPXML to HES API translation (for "garage" and "garage - unconditioned") from "vented_crawl" to "unvented_crawl", as that will align us with Foundation translation (for "Garage" = "unvented_crawl") and existing Sim Training guidance documentation.

Also, please update "Read the Docs" guidance for HVAC Distribution (https://hescore-hpxml.readthedocs.io/en/latest/translation/hvac_distribution.html) to reflect updates.

Thanks!

**Comment by nmerket** [comment]
@torstenglidden It looks like we already had this mapping done correctly for HPXML v3 and that we missed it for HPXML v2. I'll make the change.

Also, @lirainer we have the lookup logic implemented for picking duct locations that actually exist for HPXMLv3 files.

**Comment by torstenglidden** [comment]
@nmerket Excellent...thanks Noel!
