### ISSUE TITLE
Update API Test houses for v2015

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#21]

**Comment by nmerket** [comment]
@gmdickey, House 8 in the updated API test houses you provided has an assessment type of "mentor". What is that? When I look at the [HEScore API documentation](http://documentation.hescloud.net/master/api/st/xsd/submit_address_xsd.html#building_address_assessment_type), I don't see it. It's also not part of [my translator](http://hescore-hpxml.readthedocs.org/en/latest/translation/building_address.html#assessment-type).

**Comment by lirainer** [comment]
@nmerket, that change was just pushed to sandbox yesterday. We have not sent out an announcement or updated the documentation yet, sorry.

**Comment by gmdickey** [comment]
We have added that assessment type with the new version –

we have changed the certification requirements for the assessors but also included that they must be mentored during their first Score.  This type allows us to track that.



Glenn Dickey
Residential Buildings Technical Director
SRA International, Inc.
6003 Executive Boulevard, #400
Rockville, MD 20852
240-514-2859 (desk)
240-514-2601 (fax)

**Comment by nmerket** [comment]
This is a problem because we have no way to specify this in HPXML. The only think I can think of to do is a hacky solution to look for an `extension` element that would indicate that it is a "mentor" run. People would then need to know to insert that extension to make that choice.

**Comment by nmerket** [comment]
@lirainer If there is only one zone_roof instance is it required to have an area?

**Comment by lirainer** [comment]
Yes. Each roof and each floor needs an area. You can default these to the
footprint area.

Regards...

   ...leo

**Comment by nmerket** [comment]
@gmdickey For API house 6, the skylights need to be associated with a particular roof construction according to the API. @lirainer Does it matter which?

**Comment by lirainer** [comment]
The API allows you to put them on either roof, but the GUI always puts them on roof1 since the interface does not ask. So best to do that I think.

**Comment by nmerket** [comment]
This is done.
