### ISSUE TITLE
Access locked out

### ISSUE THREAD

**Issue by vargas055** [NREL/hescore-hpxml#225]
**Describe the bug**
It seems all access to the API is locked out even when we creater a new account it inmediately says it has 3 failed attempts

**Error Message**

```
There have been more than 3 failed login attempts. You have been locked out from logging into HPXML Toolbox.`
paste error message here
```

**To Reproduce**
Just try to log in

**Additional context**
This has hapened multiple times in the past, not sure what causes it all the credentials are hardcoded and havent chnaged in over 2 years. A self serve option to unlock the API account would be super useful

**Comment by nmerket** [comment]
This repo is being decommissioned. Please contact HES.API.Support@pnnl.gov for help with this in the future.
