### ISSUE TITLE
New hvac object

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#26]
from #14 
and https://developers.buildingsapi.lbl.gov/hescore/documentation/hescore-api-methods-2015

### Description of change

New object with up to two instances
Elements: hvac_name, hvac_fraction

### Details

heating, cooling, and hvac_distribution are now children of this object

**Comment by nmerket** [comment]
@gmdickey @lirainer 

I'm looking at the HVAC equipment in API house 4:
```
Heating system = 85% AFUE 120,000 BTU oil boiler installed in 2005 serves original house
		         8.2 HSPF 1.5 ton mini-split serves the addition	

Air conditioning = 4 ton, 13 SEER central air conditioner installed in 2005
		           1.5 ton, 15 SEER minisplit serves the addition

A/C ducts are in the crawlspace with no insulation and are air sealed
```

When I choose `heat_pump` using the web UI, it expects ducts for that heat pump. Mini-splits don't have ducts. How should I be entering these in the API?

**Comment by gmdickey** [comment]
The ducts are entered as 100 percent in conditioned space, insulated and sealed.

Glenn Dickey
Residential Buildings Technical Director
SRA International, Inc.
6003 Executive Boulevard, #400
Rockville, MD 20852
240-514-2859 (desk)
240-514-2601 (fax)
