### ISSUE TITLE
Add wood stoves

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#27]
from #14 
and https://developers.buildingsapi.lbl.gov/hescore/documentation/hescore-api-methods-2015
`heating.type` should add enum `wood_stove`
add enums `cord_wood`, `pellet_wood` to `heating.fuel_primary`

**Comment by nmerket** [comment]
@lirainer @gmdickey
HPXML has a heating system enumeration `Stove` as well as `Fireplace`. Should I be mapping fireplaces in HPXML to `wood_stove` in HEScore or should I error out?

**Comment by lirainer** [comment]
@nmerket @gmdickey
I would recommend only allowing `fireplace`. Is there a way to distinguish between `cord_wood` and `pellet_wood`?

**Comment by nmerket** [comment]
Yes the heating system type and fuel type are defined independently. Cord wood and pellet wood are separately called out in fuel types. I will allow `Fireplace`. I also think that if they have a `Stove` and indicate that it has either wood or wood pellets as the fuel that I will allow that too.

**Comment by lirainer** [comment]
Sorry, I mistyped that response. I meant to say *not* allowing `fireplace`!

**Comment by nmerket** [comment]
Oh, okay. I will *not* allow `Fireplace` then. Thanks!

**Comment by gmdickey** [comment]
You obviously do not need my input at this point, but I agree.

Glenn Dickey
Residential Buildings Technical Director
SRA International, Inc.
6003 Executive Boulevard, #400
Rockville, MD 20852
240-514-2859 (desk)
240-514-2601 (fax)
