### ISSUE TITLE
Find a mapping for the mentor assessment type

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#29]
There doesn't seem to be an HPXML `EventType` that can successfully map to the "mentor" assessment type. See [assessment type docs](http://hescore-hpxml.readthedocs.org/en/v2015/translation/building_address.html#assessment-type). This is possibly something that should be added to the next version of HPXML.

**Comment by nmerket** [comment]
@gmdickey Until we can get a `mentor` or equivalent assessment type built into HPXML, we need a workaround. [I implemented one](http://hescore-hpxml.readthedocs.org/en/v2015/translation/building_address.html#mentor-assessment-type). Let me know what you think.

**Comment by gmdickey** [comment]
That works.

Thanks,
Glenn
