### ISSUE TITLE
Translate Evap coolers as central air conditioning units

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#35]
According to direction we're giving to API users, the HPXML translator should translate an evaporative cooler as a central air conditioning unit (`split_dx`) with a SEER of 28.

@gmdickey @lirainer @jefffriesen @adamsten @gamalielL

**Comment by nmerket** [comment]
@gmdickey
Should it be 28 or 30 like RESNET?

**Comment by gmdickey** [comment]
I prefer 28.

Glenn Dickey
Residential Buildings Technical Director
SRA International, Inc.
6003 Executive Boulevard, #400
Rockville, MD 20852
240-514-2859 (desk)
