### ISSUE TITLE
Include missing "none" heating or cooling type

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#36]
For each `hvac` system output by HEScore, both a `heating` and `cooling` system are needed. For cases when it is determined that an `hvac` system doesn't have one or the other, make sure to fill it in.

@lirainer @andrulis

**Comment by andrulis** [comment]
Noel,  do you know if this fix was pushed out to the HES staging environment yet?  I am still seeing it for a different test case.

**Comment by lirainer** [comment]
@andrulis It takes us a little while to incorporate changes to the hpxml conversion into HEScore. I will let you know as soon as it has been pushed to sandbox.

**Comment by andrulis** [comment]
@lirainer Thanks again for the prompt response.  And sorry, I meant to address you instead of Noel, but some habits die hard (anything HPXML related has always been Noel)
