### ISSUE TITLE
Fix window area/quantity assumptions

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#40]
```xml
<Window>
    <SystemIdentifier id="window1" />
    <Area>18</Area>
    <Quantity>4</Quantity>
</Window>
```
There are two possible ways to interpret this:

 1. 4 windows with an area of 18 sq.ft. each.
 2. 4 windows with an area of 18 sq.ft. total.

Currently the translator does 1. It should do 2.

@andrulis @gamaliell @adamsten

**Comment by adamsten** [comment]
Yes, my vote is #2.


> On May 20, 2015, at 9:40 AM, Noel Merket <notifications@github.com> wrote:
> 
> <Window>
>     <SystemIdentifier id="window1" />
>     <Area>18</Area>
>     <Quantity>4</Quantity>
> </Window>
> There are two possible ways to interpret this:
> 
> 4 windows with an area of 18 sq.ft. each.
> 4 windows with an area of 18 sq.ft. total.
> Currently the translator does 1. It should do 2.
> 
> @andrulis <https://github.com/andrulis> @gamaliell <https://github.com/gamaliell> @adamsten <https://github.com/adamsten>
> —
> Reply to this email directly or view it on GitHub <https://github.com/NREL/hescore-hpxml/issues/40>.
> 


--------------------------------
Adam Stenftenagel
Co-Founder / CEO
Snugg Home
PO BOX 82
Boulder, CO
720-663-7836 x101
720-222-8604 fax
www.SnuggHome.com <http://www.snugghome.com/>
--------------------------------

**Comment by nmerket** [comment]
This is still being discussed in the HPXML working group. Hold off until a firm decision.

**Comment by GamalielL** [comment]
We need to resolve this soon, because it is holding up our HES
development.  Discussion seems to have tapered off.  How are you going to
make a decision?

**Comment by GamalielL** [comment]
Noel - Can you give us an ETA on resolving this?  How long will it take to
get this before the STC? Thanks!

**Comment by nmerket** [comment]
@GamalielL I just sent it over to them asking that. I'm probably just going to make the change here now so we can keep things moving though. I can always change it back if the STC decides to veto the majority vote of the working group.

**Comment by GamalielL** [comment]
That would be great!  Thanks!
