### ISSUE TITLE
Update weighting factor priority for HVAC

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#42]
Currently:

1. Fraction of load
1. Floor area served
1. Capacity

Should be:

1. Floor area served
1. Fraction of load
1. ~~Capacity~~

@gmdickey

**Comment by nmerket** [comment]
@gmdickey

I'm updating the API houses example hpxml files. Both House 6 and House 8 only have capacity for some of the HVAC equipment.

## House 6

> Heating system = 100,000 btu propane furnace installed in 1990
>		    2 kw of electric baseboard heat installed in 1970	
> Air conditioning = Central air conditioning, 12 SEER

## House 8

> Heating system = 100,000 btu natural gas furnace AFUE = 80 – serves 1600 sq ft
>		    50,000 btu  natural gas furnace installed in 90  - serves 600 sq ft
>		    2 kw of electric baseboard heat installed in 1970 – serves 400 sq ft	
> Air conditioning = Central air conditioning 3 tons with SEER = 13 
>    1.5 tons with SEER = 15


I need to put something in the HPXML file for these. Should I just estimate that the fraction of the load served is proportional to the capacity, or are you going to be updating them explicitly?

**Comment by gmdickey** [comment]
I have changed house 6 to


Heating system = 100,000 btu propane furnace installed in 1990 serves 2200 sq. ft.

                                    Electric baseboard heat installed in 2000 serves 400 sq. ft.



Air conditioning = Central air conditioning, 12 SEER, serves 2200 sq. ft.

And house 8 to

Heating system = 100,000 btu natural gas furnace AFUE = 80 – serves 1600 sq ft,
                            50,000 btu  natural gas furnace AFUE 90  - serves 600 sq ft
                            2 kw of electric baseboard heat installed in 1970 – serves 400 sq ft

Air conditioning = Central air conditioning 3 tons with SEER = 13 serves 2400 sq ft, servers
    1.5 tons with SEER = 15 serves 600 sq ft
     Window a/c EER 8, serves 400 sq ft

Does that seem reasonable to you.

Glenn


Glenn Dickey
Residential Buildings Technical Director
SRA International, Inc.
6003 Executive Boulevard, #400
Rockville, MD 20852
240-514-2859 (desk)

**Comment by nmerket** [comment]
Yes, I'll make the changes in the HPXML files. Thanks.

**Comment by nmerket** [comment]
One question: 
On house 8 you have heating systems serving 1600 + 600 + 400 = 2600 sq.ft.
And cooling systems serving 2400 + 600 + 400 = 3400 sq.ft.
So, more of the house is cooled than heated? Did you mean for that first central air unit to serve 1600 sq.ft. instead of 2400?

**Comment by gmdickey** [comment]
I can’t multiply.  The cooling should be the same as heating 1600, 600, 400.

Thanks for watching me.

Glenn


Glenn Dickey
Residential Buildings Technical Director
SRA International, Inc.
6003 Executive Boulevard, #400
Rockville, MD 20852
240-514-2859 (desk)

**Comment by nmerket** [comment]
No problem ;-)

**Comment by gmdickey** [comment]
I just talked to Rich.

He is going to call you to see if there is a way for the translator to take a single a/c and spread it across 2 heating zones, based on sq ft served.  If you can come up with a way to make that work, I am OK with it.

Glenn


Glenn Dickey
Residential Buildings Technical Director
SRA International, Inc.
6003 Executive Boulevard, #400
Rockville, MD 20852
240-514-2859 (desk)

**Comment by nmerket** [comment]
fixed
