### ISSUE TITLE
Include continuous insulation R-values in roof and maybe wall R-value calcs

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#44]
@lirainer

Up until now I have been assuming that when the "w/rigid foam insulation" roof assembly codes are selected, the R-value of the rigid foam was accounted for and that the specified R-value in the assembly code was additional cavity R-value. I have therefore been excluding those R-values when determining those assembly codes [as documented](http://hescore-hpxml.readthedocs.org/en/latest/translation/zone_roof.html#rigid-foam-sheathing). @gmdickey has corrected me that the R-value should include the rigid foam R-value. Is that correct?

Which brings me to my next question: What do the [R-values in the assembly codes](http://hescore-hpxml.readthedocs.org/en/latest/translation/zone_wall.html#id3) for "Wood Frame w/insulated sheathing" mean? Does that include the sheathing?

**Comment by nmerket** [comment]
@lirainer Did you see this ticket? I have a few questions for you before I can proceed.

**Comment by lirainer** [comment]
@nmerket Sorry, must have let that one slip by :confused: 

HES roof construction details are outlined [here](https://sites.google.com/a/lbl.gov/hes-public/calculation-methodology/calculation-of-energy-consumption/heating-and-cooling-calculation/building-envelope/roof-construction-types). Note that the R-value refers to the insulation between the studs and does not include the added sheathing value. Same is true for [walls](https://sites.google.com/a/lbl.gov/hes-public/calculation-methodology/calculation-of-energy-consumption/heating-and-cooling-calculation/building-envelope/wall-construction-types). So it looks to me like you are doing it correctly.

**Comment by nmerket** [comment]
The problem we're having is when someone submits a roof assembly with a layer of like R-20 rigid foam and no cavity insulation on the roof. I am counting that R-20 of continuous rigid foam in the HPXML as the 1-inch of EPS in the construction code and then passing a cavity R-value of zero because there's no cavity insulation. Is that right according to how HEScore assessors ~~would~~ should do it enter that?

**Comment by gmdickey** [comment]
Noel,

Since it looks like you don’t need to make any changes here, can you provide an HPXML translator that includes the changes for the HVAC fraction today?

Leo, if he can do that, I think we can push all the updates to sandbox.

Glenn


Glenn Dickey
Residential Buildings Technical Director
SRA International, Inc.
6003 Executive Boulevard, #400
Rockville, MD 20852
240-514-2859 (desk)

**Comment by nmerket** [comment]
@gmdickey, once I get confirmation from @lirainer that I'm doing it right even though I'm causing it to ignore a lot of insulation, I'll close this out.

**Comment by lirainer** [comment]
@nmerket Sorry, it looks like I wrote a response but never hit *Comment*!  

I would recommend the following if there is a “continuous” `InstallationType` specified:

```
AssemblyRval = ContinuousRval + CavityRval - 5
```
Then submit an assembly code of `rfps[AssemblyRval][finish]`.

Does that make sense?

**Comment by nmerket** [comment]
That makes sense to me. I'll get er done.

**Comment by nmerket** [comment]
@lirainer I am assuming I should do the same for walls, correct?

**Comment by lirainer** [comment]
@nmerket Yes.
