### ISSUE TITLE
Two-to-one heating/cooling systems

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#45]
Try to find a way to handle cases such as:

Heating | Cooling
-----|-------
Boiler - 80% | Central Air - 100 %
Baseboard - 20 % | 

by artifically splitting the cooling system for HEScore as in

Heating | Cooling | Fraction
-----|-------|-----
Boiler | Central Air | 80%
Baseboard | Central Air | 20%

Also handle cases where there are two cooling and one heating system

@andrulis @gmdickey @lirainer

**Comment by lirainer** [comment]
@nmerket Here is a set of three possible hvac configurations for testing:
![image](https://cloud.githubusercontent.com/assets/7051915/8257548/3b236784-1663-11e5-85e1-0ff56890919c.png)

**Comment by nmerket** [comment]
Unfortunately this one is going to be sort of involved. Pretty much a re-write of the HVAC sorting and combining. I'm not going to be able to code it up today before I leave on vacation for the next week. Sorry. 

However, I think I have a plan for how to apply logic for combining the heating and cooling systems in HPXML into combined HVAC systems in HEScore. I'm going to document it here so I don't forget it:

1. Get heating and cooling weights for each heating and cooling system.
1. Match heating and cooling systems by distribution systems.
  - Verify that the heating and cooling weights are within some tolerance of each other. Throw an error if not.
1. Match mini-split heat pumps by their IDs. (They're the same HPXML element so the ID will match.)
  - Add fictitious "ducts" in conditioned space.
1. Match remaining heating and cooling systems by sorting each by weight and pairing by same/similar weights within some tolerance.
  - This puts together systems without shared distribution systems such as a boiler and central air unit that serve the same area.
1. If there are any left that haven't been linked, split the "bigger" systems to match the "smaller" ones, which addresses the issue in this ticket. 
1. Pick the largest two combined systems for output to HEScore.

**Comment by nmerket** [comment]
@lirainer for the second test case above, I'm having trouble figuring out how the ducts are arranged. The arrangement is:

### Heating

 - Furnace 60%
 - Baseboards 40%

### Cooling

 - Central Air 100%

### Ducts
 - Do the furnace and central air have separate duct systems?
 - If so, when splitting the central air across the furnace and baseboard hvac systems, which duct system do I use? (I have it doing the furnace ducts so they show up somewhere.)
 - If the furnace and central air share a duct system they should serve the same (or close to the same) area, which they are not. I have some code that checks this and errors out if the fractions of the load served for a heating and cooling system on the same ducts are more than 5% different.

**Comment by nmerket** [comment]
@gmdickey quick question:

For house 8, I'm assuming given the three systems available the appropriate downselect would be to drop the baseboard heating and window air conditioner.

| Heating | Area Served | Cooling | Area Served |
|---------------------------------------------------|-------------|--------------------------------------------------|-------------|
| 100,000 btu natural gas furnace AFUE = 80 | 1600 sq ft | Central air conditioning 3 tons with SEER = 13 | 1600 sq ft |
| 50,000 btu natural gas furnace AFUE 90 | 600 sq ft | Central air conditioning 1.5 tons with SEER = 15 | 600 sq ft |
| 2 kw of electric baseboard heat installed in 1970 | 400 sq ft | Window a/c EER 8 | 400 sq ft |

**Comment by gmdickey** [comment]
yes

Glenn Dickey
Residential Buildings Technical Director
SRA International, Inc.
6003 Executive Boulevard, #400
Rockville, MD 20852
240-514-2859 (desk)

**Comment by lirainer** [comment]
I guess this is why we have use-cases.  For the case as I have written it the only reasonable way to install the AC would be as two systems, one for the central and one for the baseboard. So I think we should split that into two use-cases: one as is, where you should assume two AC units. The second would be to replace the central furnace with a wall furnace (no ducts), and a single AC to serve both zones. But both use-cases would end up being modeled similarly:  60% furnace / central AC, 40% baseboard / central AC. Would your logic work for these two cases?

**Comment by andrulis** [comment]
At the risk of adding more confusion to this process, I did want to call out another use case to think about is when the heating use is split by time, not area.  It is quite common here in the north-east to have a backup heating system that kicks in only when the primary is insufficient to meet the heating load.  In this case,  the furnace provides 60% of the heating load and the baseboard the rest, but there is only one zone so the single AC can provide the full cooling load.  

My understanding from discussions with Glenn is that HES is not currently set up this way, so this may need to wait,  but it is a pretty common use case (at least here in the frozen north :-). That is how our software was set up and has been the main stumbling block with our acceptance testing translating this to HES (and yes,  we have limitations on our side as well,  this is not to point fingers, just calling out the use case).  

Noel,  this may also be a limitation in HPXML that there is not a really good way to indicate if a HVAC system is a 'backup' or is a second primary covering a different part of the house.  Unless I am missing something there.

**Comment by lirainer** [comment]
@andrulis That is a good point. I believe the two hvac systems are being used that way in the Scoring Tool to model supplemental wood heat. Not the best, but all that we can do for now.

**Comment by nmerket** [comment]
@andrulis the use case you describe possibly does point out a deficiency in HPXML. I think we're close in that we can specify zones and which equipment serves which zones. Then you can say that both HVAC equipments serve the same zone, but the primary/secondary relationship is probably missing. There is an overall primary heating and cooling system element, but I don't think that it's sufficient. You're always welcome to create a branch on http://github.com/hpxmlwg/hpxml and pull request some changes you think would make it work. :-)
