### ISSUE TITLE
Walls with external insulation and less than R-16 total fail

### ISSUE THREAD

**Issue by lirainer** [NREL/hescore-hpxml#47]
If a file is submitted with less than R-16 total, such as:
```
                            <Layer>
                                <InstallationType>cavity</InstallationType>
                                <NominalRValue>8</NominalRValue>
                            </Layer>
                            <Layer>
                                <InstallationType>continuous</InstallationType>
                                <InsulationMaterial>
                                    <Rigid>eps</Rigid>
                                </InsulationMaterial>
                                <NominalRValue>5</NominalRValue>
                            </Layer>
```
The translator fails with:
```
  File "../code/hpxml_to_hescore.py", line 1298, in _get_building_zone_wall
    eff_rvalue = wall_eff_rvalues[const_type][ext_finish][rvalue]
KeyError: 7
```

Problem is at [line 1263](https://github.com/NREL/hescore-hpxml/blob/master/code/hpxml_to_hescore.py#L1263):
```
wall_eff_rvalues['ps'] = dict(zip(wall_ext_finish_types[:-1], [dict(zip((11, 13, 15, 19, 21), x))
```

There are *ewps* assembly codes for 00, 03, and 07 but they were not included in the *effective R-value* tables for some reason. I will do runs for the missing values and attach.

Should trap errors for missing assembly codes though, such as *ewov* less than R19.

**Comment by nmerket** [comment]
@lirainer I see the problem. What would be a good error message to display upon trapping that error? Also, do you have the list of new effective R-values you'd like me to use?

**Comment by lirainer** [comment]
@nmerket Error message should be something like "Envelope construction not supported".

Effective R-values (not sure why the markdown isn't working):
assembly code | Uval | Rval
------------- | ------ | -------
ewps00wo | 0.104 | 9.6
ewps00st | 0.121 | 8.3
ewps00vi | 0.112 | 8.9
ewps00al | 0.114 | 8.8
ewps00br | 0.103 | 9.7
ewps03wo | 0.083 | 12.0
ewps03st | 0.092 | 10.9
ewps03vi | 0.088 | 11.4
ewps03al | 0.089 | 11.2
ewps03br | 0.082 | 12.2
ewps07wo | 0.067 | 14.9
ewps07st | 0.074 | 13.5
ewps07vi | 0.071 | 14.1
ewps07al | 0.071 | 14.1
ewps07br | 0.067 | 14.9

**Comment by nmerket** [comment]
@lirainer One more question. Now that we have this working, it doesn't error out, for instance, on the OVE construction codes when the R-value is even down to zero. I have it picking the nearest R-value construction code, which if it is the less than the lowest one, it just picks the lowest one. Should it be erroring out instead? Even if the lowest construction code is R-19 and we have R-18?

**Comment by lirainer** [comment]
@nmerket Good question. I think we definitely need to error out for large differences. Since almost all our r-val spacing is < 6 throw an error if abs(desired - selected) > 3. This will work for all our assembly codes except for if someone submits a ceiling R-val of 53-56 since we only have ecwf49 and ecwf60. You would have to add an exception to allow for that. Would that work?

**Comment by lirainer** [comment]
@nmerket If you add this error are we ready to go with this fix? We are going to do a push this weekend and I would like to try and include this.

**Comment by nmerket** [comment]
@lirainer I'm thinking that it should only throw that error if the R-value more than 3 less than the lowest or more than 3 greater than the highest R-values. And yes, this is ready when the new error message is in.

**Comment by lirainer** [comment]
@nmerket :+
