### ISSUE TITLE
Efficiency required in HPXML for heating types that don't require it in HES

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#50]
From @lirainer 

> Brandon Gallagher (@brandongallagher) with Cake Systems has found an issue with the hpxml translator: HES does not require an efficiency to be submitted if the heating system is electric furnace, electric baseboard, or wood stove. In these cases we use a default efficiency value which the user cannot modify. HPXML however requires an efficiency for electric furnaces (and I assume electric baseboard and wood heat, though I have not tested it). We have two options for dealing with this: 1) allow the efficiency input to be missing in HPXML for these system types, or 2) Add documentation that tells the user to always submit an efficiency but that it will be ignored for these system types. Not sure which to recommend as both have issues. 1) would require the user to modify valid HPXML just for the scoring tool, while 2) would not be modeling what the user submitted. Any thoughts?

HPXML itself doesn't require an efficiency for electric furnaces, etc. The translator may. I'm going to look into that. We should allow the efficiency *to be missing* for the heating types that don't require it in HEScore (option 1).

**Comment by lirainer** [comment]
@nmerket Any estimate on when you might get to this one? No rush, just that we are planning a push to production 11/10 and could include this.

**Comment by nmerket** [comment]
@lirainer Should be good to go.

**Comment by lirainer** [comment]
@nmerket Works for me. Thanks!
