### ISSUE TITLE
Townhouse wall error

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#52]
When there are walls specified for each direction on the house and the house has attached walls, the translator errors out expecting there to be walls adjacent to ambient on shared walls. This shouldn't happen. 

@brandongallagher

**Comment by brandongallagher** [comment]
Thanks Noel.  Just to clarify, you are saying that there is a bug in the
translator and that my xml should have worked?

-brandon

**Comment by nmerket** [comment]
Yes, there is a bug. I'll let you know when it's ready. It usually takes a while for them to pull changes from here into sandbox and production.
