### ISSUE TITLE
Finished vs Conditioned Basement

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#54]
@gmdickey @lirainer 

Basement foundation types in HPXML have two separate true/false sub-elements to describe finished and conditioned states.

![hpxml_foundationtype](https://cloud.githubusercontent.com/assets/5325034/12830443/96576d0a-cb4c-11e5-8197-a12a129a3781.png)

When [determining the foundation type in HEScore](http://hescore-hpxml.readthedocs.org/en/latest/translation/zone_floor.html#foundation-type), it only looks for the `Conditioned` sub-element and if it's true, then you get a `cond_basement`, otherwise you get an `uncond_basement`. 

I'm running some HPXML files that have their `FoundationType` described as follows:

```xml
<Foundation>
    <SystemIdentifier id="foundation01"/>
    <FoundationType>
        <Basement>
            <Finished>true</Finished>
        </Basement>
    ...
</Foundation>
```

So, HEScore was simulating an unconditioned basement.

It was easy enough to add the appropriate `<Conditioned>true</Conditioned>` element, but it got me wondering if the translator should be looking for the `Finished` element too and assuming that finished basements are also conditioned if it's not directly called out.

What are your thoughts?

**Comment by lirainer** [comment]
@nmerket I think how you have it is correct - we should only use cond_basement if Basement/Conditioned is true. This indicates that there are actually registers that deliver heat to the space. If the space is "finished", but not "conditioned", in that it gets heated by ducts/equipment that are in the space, then it should be modeled as uncond_basement with hvac_distribution/location=uncond_basement, which will use the appropriate regain calculation. This is an ongoing controversy/discussion and I'm looking forward to what the opinion of @gmdickey is on this too!

**Comment by gmdickey** [comment]
I concur with Mr. Rainer.

New email address: glenn.dickey@csra.com

Glenn Dickey
Residential Buildings Technical Director
SRA International, Inc., A CSRA Company
6003 Executive Boulevard, #400
Rockville, MD 20852
240-514-2859 (desk)
