### ISSUE TITLE
Package the script so it can be installed with pip

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#55]
I'd like to package this script up using the [appropriate python tools](https://packaging.python.org/en/latest/distributing/). There are a couple of advantages of doing this:
1. Installation would be simpler. It'd be as simple as `pip install hescore-hpxml`. All library dependencies would be just handled automagically.
2. Updates could be as simple as `pip install --upgrade hescore-hpxml`
3. It would include a command-line script installed that could be used anywhere.

The disadvantage is that it would break your current implementation because I'd have to move some files in the repo.

What do you think?
@lirainer

**Comment by lirainer** [comment]
@nmerket Moving location of files is not a problem as we currently manually pull versions of the script. I think using pip for updates will work well, but I need to check with our developers.

**Comment by lirainer** [comment]
@nmerket We do not foresee any issues with moving to pip so please proceed as convenient. How do you want to coordinate this change with merging of the 2016 branch?

**Comment by nmerket** [comment]
@lirainer I just merged the v2016 branch into master as it looks like we're at a point where there won't be anymore v2015 hotfixes. I am going to go ahead and start rearranging things to make this pip installable.

**Comment by lirainer** [comment]
@nmerket Release of the new code (now *2017*) is set for January 17th. If there are any issues with v2015 hpxml conversion between now and then they will just have to wait. That would be a good time for us to implement the pip install too. Let me know when it is ready to test.

**Comment by nmerket** [comment]
Fixed in #67.
