### ISSUE TITLE
Allow propane for wall heaters

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#57]
Need to add the proper fuel types [here](https://github.com/NREL/hescore-hpxml/blob/f354682fbcc728587a260539507dcfb45c719c1c/code/hpxml_to_hescore.py#L313). Are there others I should be adding?

@adamsten @gmdickey @lirainer

**Comment by adamsten** [comment]
Here’s what we allow in Snugg Pro. However, I don’t see a case for solar hot water in your system. HPXML allows it as an enum, so up to you how to handle it. Also, gchp used below should probably be referred to as gshp, but it looks consistent throughout the code at least.


allowed_fuel_types = {'heat_pump': ('electric',),
                      'central_furnace': ('natural_gas', 'lpg', 'fuel_oil', 'electric', 'pellet_wood', 'cord_wood', 'solar hot water'),
                      'wall_furnace': ('natural_gas','lpg', 'electric'),
                      'baseboard': ('electric',),
                      'boiler': ('natural_gas', 'lpg', 'fuel_oil', 'electric', 'pellet_wood', 'cord_wood', 'solar hot water'),
                      'gchp': ('electric',),
                      'none': tuple(),
                      'wood_stove': ('cord_wood', 'pellet_wood')}

> On Jul 13, 2016, at 12:54 PM, Noel Merket <notifications@github.com> wrote:
> 
> Need to add the proper fuel types here <https://github.com/NREL/hescore-hpxml/blob/f354682fbcc728587a260539507dcfb45c719c1c/code/hpxml_to_hescore.py#L313>. Are there others I should be adding?
> 
> @adamsten <https://github.com/adamsten> @gmdickey <https://github.com/gmdickey> @lirainer <https://github.com/lirainer>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/NREL/hescore-hpxml/issues/57>, or mute the thread <https://github.com/notifications/unsubscribe/ABV2SArdQM_3-1cOoe3jIE-dao7p7pdmks5qVTRNgaJpZM4JLvAS>.
> 


--------------------------------
Adam Stenftenagel
Co-Founder / CEO
Snugg Home
PO BOX 82
Boulder, CO
720-663-7836 x101
www.SnuggHome.com <http://www.snugghome.com/>
--------------------------------

**Comment by nmerket** [comment]
@adamsten are these from the HEScore documentation somewhere?

**Comment by adamsten** [comment]
No.. I just filled out your code to match what might come from us. It’s just a suggestion. Our users might try to send any of this data, so we need a way to either tell them they can’t score that house because of the choice or they need to change the choice. This is something Glenn was looking into as well. 


> On Jul 13, 2016, at 1:47 PM, Noel Merket <notifications@github.com> wrote:
> 
> @adamsten <https://github.com/adamsten> are these from the HEScore documentation somewhere?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/NREL/hescore-hpxml/issues/57#issuecomment-232466059>, or mute the thread <https://github.com/notifications/unsubscribe/ABV2SGyvJY63-oC4ByvZTFFX39ZdXuU5ks5qVUDvgaJpZM4JLvAS>.
> 


--------------------------------
Adam Stenftenagel
Co-Founder / CEO
Snugg Home
PO BOX 82
Boulder, CO
720-663-7836 x101
www.SnuggHome.com <http://www.snugghome.com/>
--------------------------------

**Comment by nmerket** [comment]
Since the GUI doesn't allow propane wall heaters but the regular HEScore API does, @gmdickey and @lirainer decided that this should be consistent with the GUI and this will remain as is.
