### ISSUE TITLE
Add solar screen to windows and skylights

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#78]
New element in [zone_window](http://hes-documentation.labworks.org/home/api-definitions/api-methods/submit-inputs/building/zone/zone_wall/zone_window) and [zone_skylight](http://hes-documentation.labworks.org/home/api-definitions/api-methods/submit-inputs/building/zone/zone_roof/zone_skylight): `solar_screen`, xsd:bool, optional

**Comment by nmerket** [comment]
solar screen is in 
- https://hpxml.nrel.gov/datadictionary/2.3.0/Building/BuildingDetails/Enclosure/Windows/Window/Treatments
- https://hpxml.nrel.gov/datadictionary/2.3.0/Building/BuildingDetails/Enclosure/Windows/Window/ExteriorShading

**Comment by lirainer** [comment]
Note that the enumerations are inconsistent: `solar screen` and `solar screens`. For HEScore HPXML export we use `ExteriorShading`.

**Comment by yzhou601** [comment]
See branch "solarscreens" for updates

**Comment by nmerket** [comment]
Closed with #83
