### ISSUE TITLE
New duct location validation

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#82]
![image](https://user-images.githubusercontent.com/5325034/54387803-edfc0780-4661-11e9-8217-d14fe0d48a7b.png)

@lirainer Does this need to be done here or will the HEScore API catch this?

**Comment by lirainer** [comment]
@nmerket This is a cross-object validation done in the calculation method, so yes it will be caught. But I think it would be a good idea to reject it at hpxml input also.

**Comment by nmerket** [comment]
Think you can take this one @yzhou601?
