### ISSUE TITLE
Knee Wall Area Accounting

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#91]
In houses with knee walls, the area of the knee walls should be added to the attic floor area.  If the insulation for the knee walls is different than the attic floor, do a UA calculation to determine the average R-value.   If there is a sloped ceiling area attached to the roof rafters, typical of a cape cod style house, this portion should be characterized as a cathedral ceiling.

@gmdickey

**Comment by nmerket** [comment]
@lirainer Is this going to mess up the footprint calculation checking?

**Comment by lirainer** [comment]
@nmerket Only if we start doing it. We currently do not do any checking of roof and floor areas. @gmdickey any plans?

**Comment by nmerket** [comment]
I think we're good then.
