### ISSUE TITLE
Window code mapping changes

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#96]
- Aluminum, double pane, low-e is currently mapping to `dcaa`.
 - Aluminum, thermal break is currently mapping to `dcab`

@lirainer What should these be mapping to?

**Comment by lirainer** [comment]
- Aluminum, double pane, low-e should map to `dseaa`
- Aluminum, thermal break double clear mapping to `dcab` is correct
- Aluminum, thermal break double low-e should map to `dseab`
