### ISSUE TITLE
Cooling only mini splits

### ISSUE THREAD

**Issue by nmerket** [NREL/hescore-hpxml#97]
We are mapping cooling only mini splits to `split_dx` as described [here](https://hescore-hpxml.readthedocs.io/en/latest/translation/cooling_system.html#id2). HEScore has been updated to handle a cooling only mini split and it should be translated as such now. 

- [ ] Code changes
- [ ] Testing
- [ ] Docs

**Comment by nmerket** [comment]
@lirainer In the [HEScore docs](https://hes-documentation.labworks.org/home/api-definitions/api-methods/submit-inputs/cooling) it says

> If [cooling] type is set to `heat_pump`, `gchp`, or `mini_split` then the submitted heating/type must either match or be set to `none`.

So, would this only apply if there is no heating, or did that change and the documentation didn't?

**Comment by yzhou601** [comment]
@lirainer To make it clear, what would the ideal Json output for the test file `window_minisplit.xml` be? Would it be one hvac *( furnace heating + mini_split cooling)* or two hvac systems *( furnace heating + none cooling and none heating + mini_split cooling)*? Not sure which format would be supported by HEScore API.

**Comment by lirainer** [comment]
@nmerket That documentation is out of date (I will contact PNNL about getting it updated). PNNL now keeps their own version of the validation rules, but they should match ours which are [here](https://docs.google.com/spreadsheets/d/e/2PACX-1vTQxSzP_aCvqRXvQZUnk7nEt4IMjfoPLjniZLbf4-76Jjk8IoviJeRunpDI-laBbU3yAO2aYPyjzotM/pubhtml?gid=1&single=true). For cooling and heating `type` they are:
```
if cooling.type == none heating.type cannot be none
if cooling.type == mini_split heating.type cannot be heat_pump or gchp
if cooling.type == gchp heating.type must be gchp or wood_stove or none
if cooling.type == heat_pump heating.type must be heat_pump or wood_stove or none
if cooling.type == split_dx heating.type cannot be heat_pump or gchp or mini_split
```
@yzhou601 There is not a `window_minisplit.xml` test file, are you referring to `hvac_minisplit.xml`?  That has a mini_split, but for both heating and cooling. I have not added a test file for `mini_split cooling / furnace heating`, but it would have an expected output of one hvac system.

**Comment by yzhou601** [comment]
@lirainer Sorry it was attached in an old email about two months ago forwarded to me by Noel. But no worries. Thanks for clarifying, I will move forward to allowing combination of heating system & cooling only minisplit. 
@nmerket Are we going to implement these criteria on our end?

**Comment by lirainer** [comment]
@yzhou601 My fault! I now see that I did put together that file for testing two hpxml conversion issues. And yes, the expected result would be *one* hvac system.

**Comment by nmerket** [comment]
@lirainer it seems like your validation will catch this, so maybe we're good to not implement it as well?

> ```
> if cooling.type == none heating.type cannot be none
> if cooling.type == mini_split heating.type cannot be heat_pump or gchp
> if cooling.type == gchp heating.type must be gchp or wood_stove or none
> if cooling.type == heat_pump heating.type must be heat_pump or wood_stove or none
> if cooling.type == split_dx heating.type cannot be heat_pump or gchp or mini_split
> ```

**Comment by lirainer** [comment]
@nmerket Actually a question for PNNL as they will be taking over the `submit_hpxml` method. Do you do validation on any other inputs or leave it to the API?
